### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by orangecable** [RikudouSage/LemmySchedule#1]
When logging into the application, I receive the following text:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Details**
- Instance: lemm.ee
- 2FA is enabled for my account (but there is no way to input in the GUI)

**Comment by RikudouSage** [comment]
I've added support for 2FA, please check that it works now.

**Comment by orangecable** [comment]
It works! Thanks for the quick response and fix; amazing!
