### ISSUE TITLE
Posts do not work, errors in Docker logs.

### ISSUE THREAD

**Issue by timnunes** [RikudouSage/LemmySchedule#12]
I used the Docker Compose instructions for installation. I changed the volumes (example: /home/lemmy/docker/lemmy-schedule/lemmy-schedule-cache:/opt/runtime-cache), the APP_SECRET, and the default insance.

I can access the front end and schedule posts, but I get these errors repeating in the lemmy_schedule logs:

```
  [Error]                       

  Undefined constant "SIGTERM"  

                                

Exception trace:

  at /var/www/html/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:261

 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->getSubscribedSignals() at /var/www/html/vendor/symfony/console/Application.php:1003

 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:91

 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:320

 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:80

 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:174

 Symfony\Component\Console\Application->run() at /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54

 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/html/vendor/autoload_runtime.php:29

 require_once() at /var/www/html/bin/console:11

messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--queues QUEUES] [--no-reset] [--] [<receivers>...]
```

I also get the following in the redis logs:

`1:C 05 Oct 2023 23:51:50.807 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

**Comment by RikudouSage** [comment]
Fixed in #13 and released in v1.3.3.
