### ISSUE TITLE
[Feature Request] Add day of week picker for recurring posts.

### ISSUE THREAD

**Issue by timnunes** [RikudouSage/LemmySchedule#15]
The current workflow allows recurring posts every X days from the current day. If creating the schedule on a Friday, all other posts will be in reference to Friday, for example.

A better workflow would be to have a Day picker along with the "every X days", or even easier would be an option "Every Tuesday and Thursday", for example. The community I run has a few daily posts that only get posted 2 days a week, so this would be helpful.

**Comment by RikudouSage** [comment]
This use case is already supported:

![Screenshot 2023-10-06 at 14-30-40 Schedule new post Lemmy Schedule](https://github.com/RikudouSage/LemmySchedule/assets/13106547/32314cea-cafd-49d4-80a8-62c203c160fc)

**Comment by timnunes** [comment]
Ha!

The greyed out box made me think I couldn't even click it... Thanks!
