### ISSUE TITLE
Lemmy Schedule Icon.

### ISSUE THREAD

**Issue by tiritibambix** [RikudouSage/LemmySchedule#21]
I just made this for my dashboard. You can use it. Or not.

[![lemmyschedule-0-5x.png](https://i.postimg.cc/v8LwcdMC/lemmyschedule-0-5x.png)](https://postimg.cc/QVtyywFq)

**Comment by RikudouSage** [comment]
Looks great! Any chance you have it in svg?

**Comment by tiritibambix** [comment]
Sure

![lemmysch](https://clip.steph.click/-JJwVQsi3Q6/lemmyschedule-0-5x.svg)

**Comment by RikudouSage** [comment]
Thank you!

**Comment by RikudouSage** [comment]
It's been added at https://schedule.lemmings.world
