### ISSUE TITLE
Version Check causing 500 error

### ISSUE THREAD

**Issue by hoover900** [RikudouSage/LemmySchedule#29]
**Issue:**
with version 1.7.0 and above I'm getting an '500 Internal Server Error'

**From the log:**
[Thu Feb 15 06:34:45.686938 2024] [php:notice] [pid 41] [client 192.168.1.73:56018] [critical] Uncaught PHP Exception Twig\\Error\\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "api.new_version_check" as such route does not exist.")." at /var/www/html/templates/base.html.twig line 32

Tried setting the environment variable `NEW_VERSION_CHECK` to 0 to see if it would bypass the version check, but that doesn't seem to do anything.

Attached is the complete log
[_lemmy_stack-lemmy_schedule-1_logs.txt](https://github.com/RikudouSage/LemmySchedule/files/14292430/_lemmy_stack-lemmy_schedule-1_logs.txt)

**Comment by RikudouSage** [comment]
Sorry for that, can you clear the cache? It should be `docker exec -it your_container_name bin/console cache:clear` where you replace the `your_container_name`.

**Comment by RikudouSage** [comment]
1. Stop all the containers
2. Go to the directory mapped to `/opt/runtime-cache` (`./volumes/lemmy-schedule-cache` in the example from the README) and delete everything **except** the `pools` directory.

**Comment by hoover900** [comment]
well I don't have any jobs scheduled now so  I reverted my compose back to use the latest image and all seems to working at expected. 

Since this seems to be some what of recurring issue and clearing the cache always seem to be the solution, would moving the pool folder outside of the cache folder and clearing the cache whenever the stack is started be a possible fix? or am I possibly running into a file permission issue with docker not being able to nuke files?

thanks for the help man and thanks again for all your hard work on this dope app

**Comment by hoover900** [comment]
Clearing cache resolved issue
