### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by etymotic** [RikudouSage/LemmySchedule#33]
When clicking "Create New Post" I get a 500 Internal Error.

I removed and recreated cache (and uploads). Docker changed the owner of those folders to www-data which I think is normal behavior?

I'm still getting the 500 error and

[Thu Jun 13 18:09:04.715108 2024] [php:notice] [pid 41] [client 172.20.0.1:38010] [critical] Uncaught PHP Exception Twig\\Error\\RuntimeError: "Error rendering "ScheduleComponent" component: Cannot assign null to property Symfony\\UX\\LiveComponent\\Twig\\TemplateMap::$map of type array" at /var/www/html/templates/post/create.html.twig line 201, referer: https://schedule.wetshaving.social/post/list

**Comment by wessew** [comment]
I got the same error

**Comment by RikudouSage** [comment]
This can happen if you have an invalid cache. I recommend backing up `./volumes/lemmy-schedule-cache/pools` (if you use the docker-compose from the README, otherwise just backup the pools directory from wherever you have it bound) and deleting everything inside the bound directory for cache.

**Comment by etymotic** [comment]
I've already done that. Sorry for the confusion, but when I said I recreated the cache folder, I just made an empty folder.

**Comment by wessew** [comment]
What i tried is 
docker compose stop
backing up the /volumes/lemmy-schedule-cache/ dir
rm -r on said directory
docker compose up

And still got the same error after logging in and pressing the schedule button.

**Comment by wessew** [comment]
I tried a few more things:

Remove the docker images
Remove the docker container 
Remove the entire directory 
Make a new directory and use the default docker-compose.yml (only changed secret)
docker compose up
Delete browser cache, and just to make sure open in private browsing mode.
Result: Still the same error message.
Tried this with Firefox, Chrome and Safari.

**Comment by etymotic** [comment]
@RikudouSage I assume your instance isn't running in Docker, and your instance is working on the latest version. I assume it's some sort of Docker problem with the latest version.

**Comment by RikudouSage** [comment]
Should be fixed in v1.10.3, feel free to reopen if it isn't.
